config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stand_ups
  resources :absents, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "stand_ups#index"
end

app/models/absent.rb
class Absent < ApplicationRecord
  belongs_to :user

  def self.notify
    User.all.find_each(batch_size: 50) do |user|
      Absent.create!(user: user) unless user.has_standup_today? 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stand_up.rb
class StandUp < ApplicationRecord
  belongs_to :user

  self.per_page = 5

  validates_presence_of :name, :hours

  def date
    created_at.strftime('%A, %b %d')
  end

  # @return [Boolean]
  # Check if record is editable by current_user and current date
  def editable?(current_user)
    user == current_user && created_at.to_date == Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stand_ups, class_name: "StandUp", foreign_key: "user_id"

  def to_s
    "#{first_name} #{last_name}"
  end

  # @return [Boolean]
  # Check if user has submitted any stand_up today
  def has_standup_today?
    stand_ups.where(created_at: Date.today.all_day).present?
  end
end

app/controllers/absents_controller.rb
class AbsentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @absents = Absent.all.order('created_at DESC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/csv_generator.rb
class CsvGenerator

  # @param records{Object} 
  # @param attributes{Array} 
  def initialize(records, attributes)
    @records = records
    @attributes = attributes
    @success = false
  end
  
  def to_csv
    CSV.generate(headers: true) do |csv|
      csv << @attributes
      @records.find_each(batch_size: 50) do |object|
        csv << @attributes.map{ |attr| object.send(attr) }
      end
    end
  end

  # @return [String] 
  # Returns string with attributes as header and rows containing records
  def call
    if @records.present? && @attributes.present?
      @success = true
      self.to_csv
    end
  end

  def success?
    success
  end

  private

  attr_reader :success, :records, :attributes
end

app/controllers/stand_ups_controller.rb
class StandUpsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stand_up, only: [:show, :edit, :update, :destroy]

  # GET /stand_ups
  # GET /stand_ups.json
  def index
    @stand_up = StandUp.new
    @search = StandUp.includes(:user).order('created_at DESC').ransack(params[:q])
    @stand_ups = @search.result.page(params[:page])
    attributes = %w{id name hours user date info}

    respond_to do |format|
      format.any(:html, :json) { @stand_ups }
      format.csv { send_data CsvGenerator.new(@search.result, attributes).call, filename: "logs-#{Date.today}.csv" }
    end
  end

  # GET /stand_ups/1
  # GET /stand_ups/1.json
  def show
  end

  # GET /stand_ups/new
  def new
    @stand_up = StandUp.new
  end

  # GET /stand_ups/1/edit
  def edit
    unless @stand_up.editable?(current_user)
      redirect_to stand_ups_url, notice: 'Edit not allowed' 
    end
  end

  # POST /stand_ups
  # POST /stand_ups.json
  def create
    @stand_up = StandUp.new(stand_up_params)

    respond_to do |format|
      if @stand_up.save
        format.any(:html, :js) { redirect_to stand_ups_url, status: :created, notice: 'Stand up was successfully created.' }
      else
        flash[:alert] = @stand_up.errors.full_messages.join(',')
        format.html { redirect_to stand_ups_path }
        format.json { render json: @stand_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stand_ups/1
  # PATCH/PUT /stand_ups/1.json
  def update
    respond_to do |format|
      if @stand_up.update(stand_up_params)
        format.html { redirect_to @stand_up, notice: 'Stand up was successfully updated.' }
        format.json { render :show, status: :ok, location: @stand_up }
      else
        format.html { render :edit }
        format.json { render json: @stand_up.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stand_ups/1
  # DELETE /stand_ups/1.json
  def destroy
    @stand_up.destroy
    respond_to do |format|
      format.html { redirect_to stand_ups_url, notice: 'Stand up was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stand_up
      @stand_up = StandUp.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stand_up_params
      # params.fetch(:stand_up, {}).permit(:name, :hours, :info, :user_id)
      params.require(:stand_up).permit(:name, :hours, :info, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sort_link_turbo(attribute, *args)
    sort_link(attribute, *args.push({}, { data: { turbolinks_action: 'replace' } }))
  end

  def icon(klass, text = nil)
    icon_tag = tag.i(class: klass)
    text_tag = tag.span text
    text ? tag.span(icon_tag + text_tag) : icon_tag
  end
end

app/views/absents/index.html.erb
<div class="section-body">
  <div class="card">
    <div class="card-header">
      <h4>Absent Tracker</h4>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped table-md">
          <thead>
            <tr>
              <th>User</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            <% @absents.each do |absent| %>
              <tr>
                <td><%= absent.user %></td>
                <td><%= absent.created_at.strftime('%A, %b %d') %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', stand_ups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kudo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="main-wrapper main-wrapper-1">
    <div class="navbar-bg"></div>
    <%= render 'shared/navbar' %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
    <div class="main-content">
      <%= yield %>
    </div>
  </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="main-header navbar navbar-expand navbar-black navbar-light border-bottom">
  <%= link_to 'Work Standups', root_path, class: "navbar-brand bg-white" %>
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
    </ul>
  </form>
  
  <ul class="navbar-nav">
   <li class="nav-item">
      <%= link_to 'Absent Tracker', absents_path, class: 'nav-link bg-white' %>
    </li>
    <% if user_signed_in? %> 
      <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user bg-white">
      <div class="d-sm-none d-lg-inline-block">Hi, <%= current_user.try(:first_name) %></div></a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-divider"></div>
          <%= link_to(destroy_user_session_path, class: "dropdown-item has-icon text-danger", method: :delete) do %>  
            <i class="fas fa-sign-out-alt"></i>Logout
          <% end %>
      </div>
      </li>
    <% else %> 
      <%= link_to "Sign In", new_user_session_path %> |
      <%= link_to  "Sign Up", new_user_registration_path %>
    <% end %>
  </ul>
</nav>

app/views/stand_ups/_form.html.erb
<%= form_with(model: stand_up, local: false) do |form| %>
  <div class='card'>
  <div class="form-group row card-body">
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="col-sm-4">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="col-sm-2">
      <%= form.label :hours, 'Hours' %>
      <%= form.number_field :hours, step: :any, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group m-3">
    <%= form.label :info %>
    <%= form.text_area :info, class: 'form-control' %>
  </div>
  <div class="p-3">
    <%= form.submit class: 'btn btn-success' %>
  </div>
  </div>
<% end %>
<hr/>

app/views/stand_ups/edit.html.erb
<h1>Editing Stand Up</h1>

<%= render 'form', stand_up: @stand_up %>

<%= link_to 'Show', @stand_up %> |
<%= link_to 'Back', stand_ups_path %>

app/views/stand_ups/index.html.erb
<% unless current_user.admin? %>
  <%= render 'form', stand_up: @stand_up %>
<% end %>
<div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Daily Standups List</h4>
        <div class="card-header-action">
          <%= link_to icon('fas fa-plus', 'New'), new_stand_up_path, class: 'btn btn-icon icon-left' %>
          <%= link_to icon('fas fa-download', 'Export CSV'), stand_ups_path(format: :csv, q: request.params[:q]), class: 'd-inline has-icon float-right pl-3' %> 
            <%= link_to icon('fas fa-print', 'Print Page'), 'javascript:window.print()', class: 'd-inline has-icon float-right' %>
        </div>
      </div>
      <div class="card-body">
        <%= search_form_for @search, html: { class: 'form-row' } do |f| %>
          <div class="form-group col-sm-2">
            <%= f.search_field :name_cont, class: 'form-control m-input m-input--solid', placeholder: 'Name' %>
          </div>
          <div class="form-group col-sm-6">
            <%= f.search_field :info_cont, class: 'form-control m-input m-input--solid', placeholder: 'Info' %>
          </div>
          <div class="form-group col-sm-2">
           <%= f.date_field :created_at_gteq, class: 'form-control', placeholder: 'Start date'  %>
           <%= f.date_field :created_at_lteq, class: 'form-control', placeholder: 'End date' %>
          </div>
          <div class="form-group col-sm-2 text-right">
            <%= link_to "Clear", request.path, class: "btn btn-default" %>
            <%= f.submit 'Search', name: nil, class: 'btn btn-icon icon-left btn-primary' %>
          </div>
        <% end %>
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <thead>
              <tr>
                <th><%= sort_link(@search, :name) %></th>
                <th><%= sort_link(@search, :hours) %></th>
                <th><%= sort_link(@search, :user) %></th>
                <th><%= sort_link(@search, :created_at) %></th>
                <th>Info</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @stand_ups.each do |stand_up| %>
                <tr>
                  <td><%= stand_up.name %></td>
                  <td><%= stand_up.hours %></td>
                  <td><%= stand_up.user %></td>
                  <td><%= stand_up.date %></td>
                  <td style='width:40%'><%= stand_up.info %></td>
                  <td>
                    <%= link_to icon('fas fa-eye'), stand_up, title: 'Show it', class: 'btn btn-icon btn-sm btn-info mr-1' %>
                    <%= link_to icon('fas fa-edit'), edit_stand_up_path(stand_up), title: 'Edit it', class: 'btn btn-icon btn-sm btn-warning mr-1' if stand_up.editable?(current_user) %>
                    <%= link_to icon('fas fa-trash'), stand_up, title: 'Destroy it', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @stand_ups, list_classes: %w(pagination justify-content-end) %>
          <%# link_to 'Next page', stand_ups_path(page: @page.next_number, q: request.params[:q]), data: { target: 'infinite-page.more' } unless @page.last? %>
        </div>
      </div>
    </div>
  </div>

app/views/stand_ups/new.html.erb
<h1>New Stand Up</h1>

<%= render 'form', stand_up: @stand_up %>

<%= link_to 'Back', stand_ups_path %>

app/views/stand_ups/show.html.erb
<p id="notice"><%= notice %></p>
<section class="section">

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Show Standup -  <%= @stand_up.id %></h4>
      </div>
      <div class="card-body">
        <dl class="row">
          <dt class="col-sm-3">Name:</dt>
          <dd class="col-sm-9"><%= @stand_up.name %></dd>
          <dt class="col-sm-3">Hours:</dt>
          <dd class="col-sm-9"><%= @stand_up.hours %></dd>
          <dt class="col-sm-3">User:</dt>
          <dd class="col-sm-9"><%= @stand_up.user %></dd>
          <dt class="col-sm-3">Date:</dt>
          <dd class="col-sm-9"><%= @stand_up.date %></dd>
          <dt class="col-sm-3">Info:</dt>
          <dd class="col-sm-9"><%= @stand_up.info %></dd>
        </dl>
      </div>
    </div>
  </div>
</section>

<%= link_to 'Edit', edit_stand_up_path(@stand_up) %> |
<%= link_to 'Back', stand_ups_path %>